config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'

  resources :articles, except: [:index]
  get 'articles/:id/publish', to: 'articles#publish', as: 'publish_article'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  validates :title, presence: true
  validates :content, length: { minimum: 20 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :publish]

  def index
    @articles = Article.all
    # @articles = Article.where(published: true)
  end

  def show; end

  def new
    @article = Article.new
  end

  def create
    # <input name="article[title]" >
    # parameters: { "article": {"title": "whatever the title is"} }
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path
    else
      puts "ERROR! #{@article.errors.full_messages}"
      render "new"
    end
  end

  def edit; end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render "edit"
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  def publish
    @article.update(published: !@article.published)
    redirect_to @article
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for article do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.input :image_url %>
  <%= f.submit class: "cursor-pointer hover:bg-gray-400 hover:text-gray-800 rounded-lg shadow py-3 px-4 bg-gray-800 text-white upcase" %>
<% end -%>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
 <h1 class="text-center text-2xl font-semibold">Welcome to Wikinimous 777</h1>
  <div class="mt-4">
    <% @articles.each do |a| %>
      <%= link_to article_path(a) do  %>
        <div class="mt-4">
          <h2 class="text-xl text-blue-800"><%= a.title %></h2>
          <p class="text-base text-gray-600">
            <%= a.content %>
          </p>
          <div class="text-xs flex justify-between">
            <p class="italic">Status: <%= a.published ? 'Published' : 'Not yet published' %></p>
            <%= link_to 'Publish!', '#'  %>
          </div>
        </div>
      <% end -%>
    <% end -%>
  </div>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<h1 class="text-xl font-semibold"><%= @article.title %></h1>
<div class="mb-8 flex gap-2">
  <%= link_to edit_article_path(@article) do %>
    <i class="far fa-edit text-indigo-600"></i>
  <% end -%>
  <%= link_to article_path(@article), method: :delete, data: {confirm: 'Delete?'} do %>
    <i class="fas fa-trash-alt text-indigo-600"></i>
  <% end -%>
  <%= link_to publish_article_path(@article), data: {confirm: (@article.published ? 'Unpublish?' : 'Publish?') } do %>
    <i class="fas fa-check text-<%= @article.published ? 'indigo' : 'red' %>-600"></i>
  <% end -%>
</div>

<%= image_tag(@article.image_url, alt: @article.title, class: "object-cover w-full h-48") if @article.image_url.present? %>
<p class="whitespace-pre-line"><%= @article.content %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous777</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <main class="container mx-auto mt-28 px-5">
      <div class="flex w-full justify-center">
        <div class="w-1/2">
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="fixed top-0 left-0 w-full px-4 py-3 bg-gray-800 text-white flex justify-between">
  <p>Wikinimous #777</p>
  <%= link_to '+ Article', new_article_path  %>
</div>